# Generated by Django 6.0 on 2025-12-29 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_enrollment_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('DROPPED', 'DROPPED')], default='ACTIVE', max_length=100),
        ),
    ]
